// templates/template-react-vite-ts/src/components/ConnectWallet.tsx
import { showConnect } from "@stacks/connect";

import { userSession } from "../user-session";

function authenticate() {
  showConnect({
    appDetails: {
      name: "Stacks React Starter",
      icon: window.location.origin + "/logo512.png",
    },
    redirectTo: "/",
    onFinish: () => {
      window.location.reload();
    },
    userSession,
  });
}

function disconnect() {
  userSession.signUserOut("/");
}

const ConnectWallet = () => {
  if (userSession.isUserSignedIn()) {
    return (
      <div>
        <button className="Connect" onClick={disconnect}>
          Disconnect Wallet
        </button>
        <p>mainnet: {userSession.loadUserData().profile.stxAddress.mainnet}</p>
        <p>testnet: {userSession.loadUserData().profile.stxAddress.testnet}</p>
      </div>
    );
  }

  return (
    <button className="Connect" onClick={authenticate}>
      Connect Wallet
    </button>
  );
};

export default ConnectWallet;

// templates/template-sveltekit-ts/src/lib/ConnectWallet.svelte
<script lang="ts">
  import { showConnect } from "@stacks/connect";
  import { userSession } from "$lib/stacksUserSession";

  export function authenticate() {
    showConnect({
      appDetails: {
        name: "Stacks Svelte Starter",
        icon: window.location.origin + "/svelte.png",
      },
      redirectTo: "/",
      onFinish: () => {
        window.location.reload();
      },
      userSession,
    });
  }

  export function disconnect() {
    userSession.signUserOut("/");
  }
</script>

<div>
  {#if userSession.isUserSignedIn()}
    <button on:click={disconnect}> Disconnect Wallet </button>
    <p>mainnet: {userSession.loadUserData().profile.stxAddress.mainnet}</p>
    <p>testnet: {userSession.loadUserData().profile.stxAddress.testnet}</p>
  {:else}
    <button on:click={authenticate}> Connect Wallet </button>
  {/if}
</div>

<style>
  div {
    margin-top: 8px;
  }

  button {
    margin: 8px;
    background-color: #bbb;
    border: 2px solid #777;
    border-radius: 28px;
    font-size: 18px;
    padding: 16px 24px;
  }
</style>
