// templates/template-svelte/src/App.svelte
<script>
  import svelteLogo from "./assets/svelte.svg";
  import viteLogo from "/vite.svg";
  import ConnectWallet from "./components/ConnectWallet.svelte";
  import ContractVote from "./components/ContractVote.svelte";
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>

  <h2>Svelte + Stacks.js 👋</h2>

  <!-- ConnectWallet file: `./src/components/ConnectWallet.svelte` -->
  <ConnectWallet />

  <!-- ContractVote file: `./src/components/ContractVote.svelte` -->
  <ContractVote />

  <p>
    Visit the Stacks.js
    <a
      class="Stacks"
      target="_blank"
      href="https://github.com/hirosystems/stacks.js">official repository</a
    >
    and <a class="Stacks" href="https://stacks.js.org">library reference</a> for
    more information.
  </p>

  <p>
    Check out <a
      href="https://github.com/sveltejs/kit#readme"
      target="_blank"
      rel="noreferrer">SvelteKit</a
    >, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// templates/template-vue-ts/src/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";

import StacksConnectWallet from "./components/StacksConnectWallet.vue";
import StacksContractVote from "./components/StacksContractVote.vue";
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>

  <div class="flex-center">
    <!-- StacksConnectWallet file: `./src/components/StacksConnectWallet.vue` -->
    <StacksConnectWallet />

    <!-- StacksContractVote file: `./src/components/StacksContractVote.vue` -->
    <StacksContractVote />
  </div>

  <p>
    Visit the Stacks.js
    <a
      class="Stacks"
      target="_blank"
      href="https://github.com/hirosystems/stacks.js"
      >official repository</a
    >
    and <a class="Stacks" href="https://stacks.js.org">library reference</a> for
    more information.
  </p>

  <HelloWorld />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
